### ISSUE TITLE
problem of Alpha

### ISSUE THREAD

**Issue by 2010cxy0** [Nikke-db/spine-web-player-template#2]
Thank you for creating the template, but when loading certain animations, due to alpha, white edges may appear on the loaded model. I'm not sure if this can be resolved
![360截图20240108194956419](https://github.com/Nikke-db/spine-web-player-template/assets/77905440/54550833-61e3-4ed8-8552-e35dee72a2f1)

**Comment by Koshirei** [comment]
could you send me your spine files through a cloud link or a zip ? I will take a look when I can

**Comment by 2010cxy0** [comment]
> could you send me your spine files through a cloud link or a zip ? I will take a look when I can

The attachment is the problem file. It is said that there is a problem, but in fact, it should be said that the template lacks the function of selecting alpha. This check box is available in SpineViewerWPF, Unity, or other software. Could you please see if this function can be added？
[boss_heihude_spine_001.zip](https://github.com/Nikke-db/spine-web-player-template/files/13862869/boss_heihude_spine_001.zip)
![d5e9cd937baa733c277a708380bbfb1f](https://github.com/Nikke-db/spine-web-player-template/assets/77905440/9f2ff263-515c-46b8-8d07-26eb27582068)

**Comment by Koshirei** [comment]
An update have been released with a premultipliedAlpha toggle added on top of the character list.  
Please try it out and confirm whether it suit your needs.  
If it is, feel free to close the issue. If not, let me know additional option toggle's you'd wish to have.  

I'll be honest, this project wasn't intended to go really deep so depending on what you'd like it might be possible or impossible because of the codebase. I'm focusing a lot more on my nikke spine viewer website :)

**Comment by 2010cxy0** [comment]
> An update have been released with a premultipliedAlpha toggle added on top of the character list. Please try it out and confirm whether it suit your needs. If it is, feel free to close the issue. If not, let me know additional option toggle's you'd wish to have.
> 
> I'll be honest, this project wasn't intended to go really deep so depending on what you'd like it might be possible or impossible because of the codebase. I'm focusing a lot more on my nikke spine viewer website :)

Thank you very much for your efforts, not only this, but also nikke spine viewer is an excellent work!
